# Generated by Django 4.2.11 on 2024-06-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=100)),
                ('taskDescription', models.TextField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('task_assigned', models.DateField()),
            ],
        ),
    ]
